// USER - reducer - action - service
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_OTP = 'USER_OTP';
export const USER_OTP_FAILED = 'USER_OTP_FAILED';
export const USER_OTP_SUCCESS = 'USER_OTP_SUCCESS';

export const USER_CONFIRM_OTP = 'USER_CONFIRM_OTP';
export const USER_CONFIRM_OTP_FAILED = 'USER_CONFIRM_OTP_FAILED';
export const USER_CONFIRM_OTP_SUCCESS = 'USER_CONFIRM_OTP_SUCCESS';

//PRODUCT

export const GET_PRICE_LIST_OF_BUSINESS_CARD_CATEGORY =
  'GET_PRICE_LIST_OF_BUSINESS_CARD_CATEGORY';
export const GET_PRICE_LIST_OF_BUSINESS_CARD_CATEGORY_FAILED =
  'GET_PRICE_LIST_OF_BUSINESS_CARD_CATEGORY_FAILED';
export const GET_PRICE_LIST_OF_BUSINESS_CARD_CATEGORY_SUCCESS =
  'GET_PRICE_LIST_OF_BUSINESS_CARD_CATEGORY_SUCCESS';

export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_ALL_PRODUCT_FAILED = 'GET_ALL_PRODUCT_FAILED';
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';

// ORDER
export const SEND_ORDER = 'SEND_ORDER';
export const SEND_ORDER_FAILED = 'SEND_ORDER_FAILED';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';

export const GET_ALL_ORDER = 'GET_ALL_ORDER';
export const GET_ALL_ORDER_FAILED = 'GET_ALL_ORDER_FAILED';
export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS';

// REVIEEW

export const GET_PRODUCT_REVIEW = 'GET_PRODUCT_REVIEW';
export const GET_PRODUCT_REVIEW_FAILED = 'GET_PRODUCT_REVIEW_FAILED';
export const GET_PRODUCT_REVIEW_SUCCESS = 'GET_PRODUCT_REVIEW_SUCCESS';

export const POST_PRODUCT_REVIEW = 'POST_PRODUCT_REVIEW';
export const POST_PRODUCT_REVIEW_FAILED = 'POST_PRODUCT_REVIEW_FAILED';
export const POST_PRODUCT_REVIEW_SUCCESS = 'POST_PRODUCT_REVIEW_SUCCESS';
