import {Platform, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    marginTop: Platform.OS === 'ios' ? 40 : 10,
    paddingBottom: 0,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  welcome: {
    fontSize: 25,
    fontWeight: '700',
  },
  startButtonText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    width: '100%',
    fontSize: 17,
  },
  startButton: {
    marginTop: 10,
    backgroundColor: '#228BC4',
    alignItems: 'center',
    marginBottom: 20,
  },
  ProfileRoot: {
    // flex: 1,
    paddingTop: 10,
  },
  ProfileTab: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#e1dfdf',
    borderRadius: 7,
  },
  ProfileTabText: {
    textAlign: 'center',
    fontSize: 13,
  },
  noLogConc: {marginTop: 20, marginBottom: 20},
  noLogText: {fontSize: 17, fontWeight: '100'},
  itemProdConc: {marginLeft: 30, width: 75},
  itemProdTitle: {fontSize: 13, fontWeight: 'bold'},
  itemProdSubTitle: {
    fontSize: 10,
    color: 'rgba(152, 151, 151, 1)',
  },
  card: {
    backgroundColor: '#fff',
    marginTop: 20,
    marginBottom: 10,
    padding: 20,
    paddingBottom: 15,
    borderRadius: 10,
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 25,
    borderBottomColor: '#E0DFDF',
    borderBottomWidth: 1,
    marginBottom: 20,
  },
  cardInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  cardInnerConc: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  quaConc: {flexDirection: 'row', alignItems: 'center'},
  quaButton: {
    // padding: 3,
    height: 15,
    marginLeft: 9,
    width: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#C52874',
    borderRadius: 3,
    borderWidth: 1,
    backgroundColor: '#C5287414',
  },
  quaButtontext: {fontSize: 8, color: '#C52874'},
  quaValue: {
    fontSize: 10,
    marginLeft: 9,
    fontWeight: '700',
  },
  price: {
    fontSize: 10,
    fontWeight: '700',
    width: 80,
    marginLeft: 5,
  },
  actionConc: {
    flexDirection: 'row',
  },
  blueBut: {padding: 0, width: 'auto'},
  secondActionBut: {padding: 0, width: 'auto', marginLeft: 8},
  buttonIcon: {
    fontSize: 25,
    fontWeight: '800',
    marginRight: 20,
    color: 'rgba(34, 139, 196, 1)',
  },
});
